# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  get-net:  
    runs-on: ubuntu-latest
    needs: get-code
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
  get-deps:  
    runs-on: ubuntu-latest
    needs: get-net
    steps:
    - name: Get Deps
    - run: dotnet restore

  build:  
    runs-on: ubuntu-latest
    needs: get-deps
    steps:
    - name: Build
    - run: dotnet build
    
  test:  
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Test
    - run: dotnet test
 
  
  
    
    
